version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: simple_web_stack_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-todos}
      MYSQL_USER: ${MYSQL_USER:-taskuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-taskpassword}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-utaskuser", "-ptaskpassword"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 30s

  backend:
    container_name: simple_web_stack_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: development  # Use development stage by default
    ports:
      - "3007:3007"
    environment:
      DATABASE_URL: ${DATABASE_URL:-taskuser:taskpassword@tcp(mysql:3306)/todos?parseTime=true}
      APP_BIND_ADDRESS: 0.0.0.0:3007
      GO_ENV: ${GO_ENV:-development}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      # Mount for hot reload in development
      - ./backend:/app
    working_dir: /app
    command: air

  frontend:
    container_name: simple_web_stack_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development  # Use development stage by default
    ports:
      - "8007:8007"
    environment:
      BACKEND_URL: ${BACKEND_URL:-http://backend:3007}
      PORT: "8007"
      DENO_ENV: ${DENO_ENV:-development}
    depends_on:
      - backend
    volumes:
      # Mount for hot reload in development
      - ./frontend:/app
    working_dir: /app
    command: ["deno", "task", "dev"]

volumes:
  mysql_data:
