version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "root:root@tcp(db:3306)/todos?parseTime=true"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    working_dir: /app
    command: air

  frontend:
    build: ./frontend
    ports:
      - "8001:8000"
    environment:
      BACKEND_URL: "http://backend:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: deno task dev

volumes:
  db_data:
