name: Buf Push

on:
  push:
    branches:
      - main
    paths:
      - 'proto/**'
      - '.github/workflows/buf-push.yml'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          
      - name: Push to BSR
        run: |
          cd proto
          buf push