name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  proto-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: bufbuild/buf-action@v1
        
      - name: Lint proto files
        run: |
          cd proto
          buf lint
          
      - name: Check breaking changes
        run: |
          cd proto
          buf breaking --against '.git#branch=main'

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - uses: bufbuild/buf-action@v1
          
      - name: Generate code
        run: buf generate
        
      - name: Download dependencies
        run: |
          cd backend
          go mod download
          
      - name: Run tests
        run: |
          cd backend
          go test ./...
          
      - name: Build
        run: |
          cd backend
          go build -v ./cmd/server

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          
      - uses: bufbuild/buf-action@v1
          
      - name: Generate code
        run: buf generate
        
      - name: Cache dependencies
        run: |
          cd frontend
          deno cache main.ts || true
          
      - name: Run tests
        run: |
          cd frontend
          deno test
          
      - name: Type check
        run: |
          cd frontend
          deno check **/*.ts